export interface Usuario {
  access_token?: string;
  usuario: {
    id: number;
    nombre: string;
    apellidos: string;
    email?: string;
    pronombre?: string;
    genero?: string;
    orientacion?: string;
    password?: string;
    telefono?: string;
    biografia?: string;
    fecha_nacimiento?: string;
    fotoPerfil?: string;
    fotoPublicId?: string;
    fotoCabecera?: string;
    rolPerfil: 'usuario' | 'admin' | 'moderador';
    carnet_conducir_verificado?: boolean;
    fotoDocumentoDelantera?: string;
    fotoDocumentoTrasera?: string;
    fotoCarnetCondDelantera?: string;
    fotoCarnetCondTrasera?: string;
    numero_documento?: string;
    dni_verificado?: boolean;
    numero_carnet_conducir?: string;
    preferencias?: string[];
    fecha_vencimiento_carnet?: string;
    comunic_comerciales?: boolean;
    comunic_terceros?: boolean;
    vehiculos?: any;
    created_at?: string;
    updated_at?: string;
    token?: string;
    ya_ha_sido_suspendido?: boolean;
    motivo_bloqueo?: string;
    bloqueado_desde?: Date;
    bloqueado_hasta?: Date;
    metodo_pago_preferido?: string;
    paypal_email?: string;
    tarjeta_numero?: string;
    tarjeta_exp?: string;
    metodo_cobro_preferido?: string;
    cobro_paypal_email?: string;
    cobro_iban?: string;
    cobro_titular?: string;
  };
}
