"""actualizar modelos y relaciones

Revision ID: 11a87c9c7ab7
Revises: 
Create Date: 2026-09-08 10:42:33.868837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11a87c9c7ab7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_monedero')
    op.drop_table('monederos')

    # Se eliminaron las alteraciones automáticas de las columnas 'id' para evitar conflictos con IDENTITY en PostgreSQL

    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_auth_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        batch_op.drop_column('paypal_auth_id')

    op.create_table('monederos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('monederos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saldo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='monederos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='monederos_pkey'),
    sa.UniqueConstraint('usuario_id', name='monederos_usuario_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('movimientos_monedero',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monedero_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('concepto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('saldo_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monedero_id'], ['monederos.id'], name='movimientos_monedero_monedero_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='movimientos_monedero_pkey')
    )
    # ### end Alembic commands ###