"""Añadir campos de saldo anterior y referencia a movimientos

Revision ID: 14473747fca7
Revises: 11a87c9c7ab7
Create Date: 2026-09-20 20:25:17.390742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14473747fca7'
down_revision = '11a87c9c7ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monederos', schema=None) as batch_op:
        batch_op.drop_constraint('monederos_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('movimientos_monedero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_anterior', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('saldo_actual', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('referencia_id', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('movimientos_monedero_monedero_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'monederos', ['monedero_id'], ['id'])
        batch_op.drop_column('saldo_final')

    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('movimientos_monedero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('movimientos_monedero_monedero_id_fkey', 'monederos', ['monedero_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('referencia_id')
        batch_op.drop_column('saldo_actual')
        batch_op.drop_column('saldo_anterior')

    with op.batch_alter_table('monederos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('monederos_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
