"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 200ff44bb879
Revises: 73d1873f4f6e
Create Date: 2025-02-21 22:57:29.260572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200ff44bb879'
down_revision = '73d1873f4f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
