"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 2c2e96bb54fd
Revises: 856eef36570f
Create Date: 2025-06-09 19:52:10.884399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2e96bb54fd'
down_revision = '856eef36570f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_monedero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('concepto', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monederos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monederos', schema=None) as batch_op:
        batch_op.drop_column('ultima_actualizacion')
        batch_op.drop_column('estado')

    op.drop_table('movimientos_monedero')
    # ### end Alembic commands ###
