"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 42cc7f23d312
Revises: 
Create Date: 2026-09-06 22:15:58.857855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cc7f23d312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancelaciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['cancelado_por_id'], ['id'])

    with op.batch_alter_table('conversaciones', schema=None) as batch_op:
        batch_op.alter_column('usuario1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario2_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('encuestas_satisfaccion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('historial_cambios_viajes', schema=None) as batch_op:
        batch_op.drop_constraint('historial_cambios_viajes_viaje_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'viajes', ['viaje_id'], ['id'])

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['emisor_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['receptor_id'], ['id'])

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('notificaciones_viaje_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'viajes', ['viaje_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('ordenes_paypal', schema=None) as batch_op:
        batch_op.alter_column('paypal_order_id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'usuarios', ['conductor_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['pasajero_id'], ['id'])

    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_auth_id', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('pasajeros_viaje_viaje_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'viajes', ['viaje_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('puntuaciones', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_puntuacion_usuario', 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key('fk_puntuacion_evaluador', 'usuarios', ['evaluador_id'], ['id'])

    with op.batch_alter_table('token_push', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehiculos', ['vehiculo'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('token_push', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('puntuaciones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_puntuacion_evaluador', type_='foreignkey')
        batch_op.drop_constraint('fk_puntuacion_usuario', type_='foreignkey')

    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pasajeros_viaje_viaje_id_fkey', 'viajes', ['viaje_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('paypal_auth_id')

    with op.batch_alter_table('ordenes_paypal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('paypal_order_id',
               existing_type=sa.String(length=100),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notificaciones_viaje_id_fkey', 'viajes', ['viaje_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('historial_cambios_viajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('historial_cambios_viajes_viaje_id_fkey', 'viajes', ['viaje_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('encuestas_satisfaccion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('conversaciones', schema=None) as batch_op:
        batch_op.alter_column('usuario2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario1_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cancelaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###