"""Reinicio de migraciones y tabla eventos

Revision ID: 573127ea6f67
Revises: 
Create Date: 2026-04-15 20:27:24.927586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573127ea6f67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.Column('enlace_info', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
