"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 6ced7215c7bb
Revises: 96f32464c5d6
Create Date: 2025-03-13 19:18:51.506653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ced7215c7bb'
down_revision = '96f32464c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
