"""Añadida columna reserva_automatica a viajes

Revision ID: 75796a6c7da8
Revises: 
Create Date: 2026-04-21 11:22:44.015737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75796a6c7da8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserva_automatica', sa.Boolean(), nullable=False, server_default='false'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('reserva_automatica')
    # ### end Alembic commands ###
