"""Sincronizacion final consolidada

Revision ID: 7e1148df4714
Revises: 
Create Date: 2026-04-12 13:37:17.908320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e1148df4714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monederos')
    op.drop_table('cancelaciones')
    op.drop_table('movimientos_monedero')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('puntuaciones', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_puntuacion_viaje', 'viajes', ['viaje_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint('usuarios_numero_documento_key', type_='unique')
        batch_op.drop_column('numero_carnet_conducir')
        batch_op.drop_column('carnet_conducir_verificado')
        batch_op.drop_column('numero_documento')
        batch_op.drop_column('dni_verificado')
        batch_op.drop_column('fecha_vencimiento_carnet')
        batch_op.drop_column('fotoCarnetCondDelantera')

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoCarnetCondDelantera', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_vencimiento_carnet', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dni_verificado', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_documento', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carnet_conducir_verificado', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_carnet_conducir', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('usuarios_numero_documento_key', ['numero_documento'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('puntuaciones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_puntuacion_viaje', type_='foreignkey')

    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        pass  # Asegúrate de poner el pass si comentas todo lo de abajo
        # batch_op.alter_column('id',
        #               existing_type=sa.INTEGER(),
        #

    op.create_table('movimientos_monedero',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('concepto', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='movimientos_monedero_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='movimientos_monedero_pkey')
    )
    op.create_table('cancelaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('viaje_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cancelado_por_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pasajeros_afectados', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('motivo_cancelacion_cond', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('motivo_cancelacion_pasaj', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_cancelacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['usuarios.id'], name='cancelaciones_cancelado_por_id_fkey'),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], name='cancelaciones_viaje_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cancelaciones_pkey')
    )
    op.create_table('monederos',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('saldo', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ultima_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='monederos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='monederos_pkey'),
    sa.UniqueConstraint('usuario_id', name='monederos_usuario_id_key')
    )
    # ### end Alembic commands ###
