"""Añadida columna tipo y conversacionID en notificaciones

Revision ID: 7fcf9fd08387
Revises: 
Create Date: 2026-04-21 14:42:33.957211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcf9fd08387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('conversacion_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_column('conversacion_id')
        batch_op.drop_column('tipo')
    # ### end Alembic commands ###
