"""Reset de migraciones

Revision ID: a0c5697eaf2f
Revises: 
Create Date: 2026-04-20 21:52:37.946893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0c5697eaf2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_paypal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.Column('pasajero_id', sa.Integer(), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.Column('paypal_order_id', sa.Float(), nullable=False),
    sa.Column('importe_fijado', sa.Float(), nullable=False),
    sa.Column('gastos_gestion', sa.Float(), nullable=False),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pasajero_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
  