"""Corregir relaciones con claves foráneas ambiguas

Revision ID: aaa47f3d1728
Revises: 32aaa7f61c71
Create Date: 2025-11-05 18:59:25.415070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaa47f3d1728'
down_revision = '32aaa7f61c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Crear nueva tabla y eliminar antigua
    op.create_table(
        'tokenusado',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=500), nullable=False),
        sa.Column('usado_en', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    op.drop_table('token_usado')

    with op.batch_alter_table('monederos') as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('ultima_actualizacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # -------------------------
    # TABLA PUNTUACIONES
    # -------------------------
    with op.batch_alter_table('puntuaciones', schema=None) as batch_op:


        batch_op.alter_column('puntuacion',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              nullable=False)

        batch_op.alter_column('comentario',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=500),
                              existing_nullable=True)

        batch_op.alter_column('fecha',
                              existing_type=sa.DATE(),
                              type_=sa.DateTime(),
                              existing_nullable=True)

        batch_op.alter_column('usuario_id',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              nullable=False)

        batch_op.alter_column('evaluador_id',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              nullable=False)

       #  batch_op.drop_constraint('puntuaciones_id_key', type_='unique')

    # -------------------------
    # TABLA USUARIOS
    # -------------------------
    with op.batch_alter_table('usuarios', schema=None) as batch_op:

        # FIX: evitar intentar crear columna existente
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        existing_columns = [c['name'] for c in inspector.get_columns('usuarios')]

        if 'numero_documento' not in existing_columns:
            batch_op.add_column(sa.Column('numero_documento', sa.String(length=9), nullable=True))


        batch_op.alter_column('nombre',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=120),
                              nullable=False)

        batch_op.alter_column('apellidos',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=250),
                              nullable=False)

        batch_op.alter_column('email',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=250),
                              nullable=False)

        batch_op.alter_column('genero',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=50),
                              nullable=False)

        batch_op.alter_column('orientacion',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=50),
                              nullable=False)

        batch_op.alter_column('pronombre',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=250),
                              existing_nullable=True)

        batch_op.alter_column('password',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=250),
                              nullable=False)

        batch_op.alter_column('telefono',
                              existing_type=sa.BIGINT(),
                              type_=sa.String(length=15),
                              existing_nullable=True)

        batch_op.alter_column('biografia',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=500),
                              existing_nullable=True)

        batch_op.alter_column('fotoPerfil',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=250),
                              existing_nullable=True)

        batch_op.alter_column('fotoCabecera',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=250),
                              existing_nullable=True)

        batch_op.alter_column('preferencias',
                              existing_type=postgresql.JSON(astext_type=sa.Text()),
                              nullable=False)

        batch_op.alter_column('rolPerfil',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=50),
                              existing_nullable=True)

        batch_op.alter_column('fotoCarnetCondDelantera',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=250),
                              existing_nullable=True)

        batch_op.alter_column('created_at',
                              existing_type=sa.DATE(),
                              type_=sa.DateTime(),
                              existing_nullable=True)

        batch_op.alter_column('updated_at',
                              existing_type=sa.DATE(),
                              type_=sa.DateTime(),
                              existing_nullable=True)

       #  batch_op.drop_constraint('usuarios_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['numero_documento'])
        batch_op.create_unique_constraint(None, ['telefono'])

        batch_op.drop_column('numero_carnet_conducir')
        batch_op.drop_column('fotoDocumentoDelantera')
        batch_op.drop_column('fotoDocumentoTrasera')
        batch_op.drop_column('fecha_vencimiento_carnet')
        batch_op.drop_column('fotoCarnetCondTrasera')

    # -------------------------
    # TABLA VEHICULOS
    # -------------------------
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:


        batch_op.alter_column('marca',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=100),
                              nullable=False)

        batch_op.alter_column('modelo',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=100),
                              nullable=False)

        batch_op.alter_column('color',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=100),
                              nullable=False)

        batch_op.alter_column('matricula',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=10),
                              nullable=False)

        batch_op.alter_column('fk_vehiculo_usuario',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              existing_nullable=True)

       #  batch_op.drop_constraint('vehiculos_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['matricula'])

    # -------------------------
    # TABLA VIAJES
    # -------------------------
    with op.batch_alter_table('viajes', schema=None) as batch_op:


        batch_op.alter_column('origen',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=100),
                              nullable=False)

        batch_op.alter_column('destino',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=100),
                              nullable=False)

        batch_op.alter_column('plazas',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              nullable=False)

        batch_op.alter_column('hora_salida',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=50),
                              nullable=False)

        batch_op.alter_column('hora_llegada',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=50),
                              nullable=False)

        batch_op.alter_column('precio_viaje',
                              existing_type=sa.REAL(),
                              type_=sa.Float(),
                              nullable=False)

        batch_op.alter_column('duracion_viaje',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=50),
                              existing_nullable=True)

        batch_op.alter_column('fecha_salida',
                              existing_type=sa.DATE(),
                              type_=sa.DateTime(),
                              nullable=False)

        batch_op.alter_column('ruta_seleccionada',
                              existing_type=postgresql.JSON(astext_type=sa.Text()),
                              nullable=False)

        batch_op.alter_column('usuario_id',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              nullable=False)

        batch_op.alter_column('vehiculo',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              nullable=False)

        batch_op.alter_column('created_at',
                              existing_type=sa.DATE(),
                              type_=sa.DateTime(),
                              existing_nullable=True)

       #  batch_op.drop_constraint('viajes_id_key', type_='unique')
        batch_op.drop_constraint('viajes_vehiculo_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.create_foreign_key('viajes_vehiculo_fkey', 'vehiculos', ['vehiculo'], ['id'])
       #  batch_op.create_unique_constraint('viajes_id_key', ['id'])
        batch_op.alter_column('created_at',
                              existing_type=sa.DateTime(),
                              type_=sa.DATE(),
                              existing_nullable=True)

        batch_op.alter_column('vehiculo',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              nullable=True)

        batch_op.alter_column('usuario_id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              nullable=True)

        batch_op.alter_column('ruta_seleccionada',
                              existing_type=postgresql.JSON(astext_type=sa.Text()),
                              nullable=True)

        batch_op.alter_column('fecha_salida',
                              existing_type=sa.DateTime(),
                              type_=sa.DATE(),
                              nullable=True)

        batch_op.alter_column('duracion_viaje',
                              existing_type=sa.String(length=50),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('precio_viaje',
                              existing_type=sa.Float(),
                              type_=sa.REAL(),
                              nullable=True)

        batch_op.alter_column('hora_llegada',
                              existing_type=sa.String(length=50),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('hora_salida',
                              existing_type=sa.String(length=50),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('plazas',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              nullable=True)

        batch_op.alter_column('destino',
                              existing_type=sa.String(length=100),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('origen',
                              existing_type=sa.String(length=100),
                              type_=sa.TEXT(),
                              nullable=True)


    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
       #  batch_op.create_unique_constraint('vehiculos_id_key', ['id'])

        batch_op.alter_column('fk_vehiculo_usuario',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              existing_nullable=True)

        batch_op.alter_column('matricula',
                              existing_type=sa.String(length=10),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('color',
                              existing_type=sa.String(length=100),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('modelo',
                              existing_type=sa.String(length=100),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('marca',
                              existing_type=sa.String(length=100),
                              type_=sa.TEXT(),
                              nullable=True)


    with op.batch_alter_table('usuarios', schema=None) as batch_op:

        batch_op.add_column(sa.Column('fecha_vencimiento_carnet', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('numero_carnet_conducir', sa.TEXT(), nullable=True))

        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

       #  batch_op.create_unique_constraint('usuarios_id_key', ['id'])

        batch_op.alter_column('updated_at',
                              existing_type=sa.DateTime(),
                              type_=sa.DATE(),
                              existing_nullable=True)

        batch_op.alter_column('created_at',
                              existing_type=sa.DateTime(),
                              type_=sa.DATE(),
                              existing_nullable=True)

        batch_op.alter_column('fotoCarnetCondDelantera',
                              existing_type=sa.String(length=250),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('rolPerfil',
                              existing_type=sa.String(length=50),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('preferencias',
                              existing_type=postgresql.JSON(astext_type=sa.Text()),
                              nullable=True)

        batch_op.alter_column('fotoCabecera',
                              existing_type=sa.String(length=250),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('fotoPerfil',
                              existing_type=sa.String(length=250),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('biografia',
                              existing_type=sa.String(length=500),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('telefono',
                              existing_type=sa.String(length=15),
                              type_=sa.BIGINT(),
                              existing_nullable=True)

        batch_op.alter_column('password',
                              existing_type=sa.String(length=250),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('pronombre',
                              existing_type=sa.String(length=250),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('orientacion',
                              existing_type=sa.String(length=50),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('genero',
                              existing_type=sa.String(length=50),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('email',
                              existing_type=sa.String(length=250),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('apellidos',
                              existing_type=sa.String(length=250),
                              type_=sa.TEXT(),
                              nullable=True)

        batch_op.alter_column('nombre',
                              existing_type=sa.String(length=120),
                              type_=sa.TEXT(),
                              nullable=True)

       
        batch_op.drop_column('numero_documento')

    with op.batch_alter_table('puntuaciones', schema=None) as batch_op:
       #  batch_op.create_unique_constraint('puntuaciones_id_key', ['id'])

        batch_op.alter_column('evaluador_id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              nullable=True)

        batch_op.alter_column('usuario_id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              nullable=True)

        batch_op.alter_column('fecha',
                              existing_type=sa.DateTime(),
                              type_=sa.DATE(),
                              existing_nullable=True)

        batch_op.alter_column('comentario',
                              existing_type=sa.String(length=500),
                              type_=sa.TEXT(),
                              existing_nullable=True)

        batch_op.alter_column('puntuacion',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              nullable=True)

    with op.batch_alter_table('monederos') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
       #  batch_op.create_unique_constraint('monederos_id_key', ['id'])
        batch_op.alter_column('ultima_actualizacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)




    # Restaurar tabla antigua token_usado
    op.create_table(
        'token_usado',
        sa.Column('id', sa.BIGINT(), sa.Identity(), autoincrement=True, nullable=False),
        sa.Column('token', sa.TEXT(), nullable=True),
        sa.Column('usado_en', sa.DATE(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='token_usado_pkey'),
       #  sa.UniqueConstraint('id', name='token_usado_id_key')
    )

    op.drop_table('tokenusado')
    # ### end Alembic commands ###
