"""Corregir relaciones con claves foráneas ambiguas

Revision ID: ca961ef82b6a
Revises: 6ced7215c7bb
Create Date: 2025-03-18 15:09:40.316259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca961ef82b6a'
down_revision = '6ced7215c7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehiculo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('vehiculo')

    # ### end Alembic commands ###
