"""Corregir relaciones con claves foráneas ambiguas

Revision ID: dbae40dd18ed
Revises: aaa47f3d1728
Create Date: 2025-11-25 14:22:40.685901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbae40dd18ed'
down_revision = 'aaa47f3d1728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###










    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_documento', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('fotoCarnetCondDelantera', sa.String(length=250), nullable=True))
       
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    
        batch_op.create_unique_constraint(None, ['numero_documento'])





    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

       


       

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
  
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        
        batch_op.drop_column('fotoCarnetCondDelantera')
        batch_op.drop_column('numero_documento')


       

  
    # ### end Alembic commands ###