"""test

Revision ID: fb0749f2c8b4
Revises: 7e1148df4714
Create Date: 2026-04-12 13:39:40.298433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb0749f2c8b4'
down_revision = '7e1148df4714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Borramos las tablas que ya no quieres en el proyecto
    op.drop_table('cancelaciones')
    op.drop_table('movimientos_monedero')
    op.drop_table('monederos')

    # 2. Comentamos las alteraciones de ID en notificaciones
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        pass
        # batch_op.alter_column('id',
        #        existing_type=sa.INTEGER(),
        #        server_default=None,
        #        existing_nullable=False,
        #        autoincrement=True)

    # 3. Comentamos las alteraciones de ID en pasajeros_viaje
    with op.batch_alter_table('pasajeros_viaje', schema=None) as batch_op:
        pass
        # batch_op.alter_column('id',
        #        existing_type=sa.INTEGER(),
        #        server_default=None,
        #        existing_nullable=False,
        #        autoincrement=True)

    # 4. Creamos la llave foránea que faltaba en puntuaciones
    with op.batch_alter_table('puntuaciones', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_puntuacion_viaje', 'viajes', ['viaje_id'], ['id'])

    # 5. Limpiamos la tabla usuarios (quitando columnas viejas)
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        # batch_op.alter_column('id',
        #        existing_type=sa.INTEGER(),
        #        server_default=None,
        #        existing_nullable=False,
        #        autoincrement=True)
        batch_op.drop_constraint('usuarios_numero_documento_key', type_='unique')
        batch_op.drop_column('numero_documento')
        batch_op.drop_column('carnet_conducir_verificado')
        batch_op.drop_column('fecha_vencimiento_carnet')
        batch_op.drop_column('fotoCarnetCondDelantera')
        batch_op.drop_column('numero_carnet_conducir')
        batch_op.drop_column('dni_verificado')

    # 6. Comentamos alteraciones de ID en vehiculos
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        pass
        # batch_op.alter_column('id',
        #        existing_type=sa.INTEGER(),
        #        server_default=None,
        #        existing_nullable=False,
        #        autoincrement=True)

    # 7. Comentamos alteraciones de ID en viajes
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        pass
        # batch_op.alter_column('id',
        #        existing_type=sa.INTEGER(),
        #        server_default=None,
        #        existing_nullable=False,
        #        autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # El downgrade se deja como estaba por si alguna vez necesitas revertir, 
    # aunque lo ideal es no tocarlo si no vas a volver atrás.
    pass